apiVersion: v1
kind: Secret
metadata:
  name: {{ include "$$PROJECT_NAME$$.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "$$PROJECT_NAME$$.name" . }}-app
    helm.sh/chart: {{ include "$$PROJECT_NAME$$.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-app
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  secret_key: {{.Values.app.secretKey | b64enc | quote }}
