apiVersion: v1
kind: Service
metadata:
  name: {{ include "$$PROJECT_NAME$$.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "$$PROJECT_NAME$$.name" . }}-app
    helm.sh/chart: {{ include "$$PROJECT_NAME$$.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: 8000
      protocol: TCP
      name: app-http
  selector:
    app.kubernetes.io/name: {{ include "$$PROJECT_NAME$$.name" . }}-app
    app.kubernetes.io/instance: {{ .Release.Name }}

