
appImageTag: master

postgresql:
  image:
    pullPolicy: Always
  global:
    storageClass: nfs-client
    postgresql:
      auth:
        postgresPassword: NotAVeryGoodPassword
        password: StillNotAVeryGoodPassword


nginx:
  image:
    pullPolicy: Always
  addLabels:
    deployDate: CISetDate

app:
  image:
    pullPolicy: Always
  addLabels:
    deployDate: CISetDate
  secretKey: SECRET_KEY

imagePullSecrets:
  - name: gitlab

ingress:
  enabled: true 
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - $$PROJECT_NAME$$-master.my.hostname.com
  tls: 
    - hosts:
      - $$PROJECT_NAME$$-master.my.hostname.com
      secretName: $$PROJECT_NAME$$-master-tls
