
appImageTag: 1.0.0

postgresql:
  persistence:
    storageClass: nfs-client
  postgresqlPassword: SETAPASSWORD

nginx:
  addLabels:
    deployDate: TODAY

app:
  addLabels:
    deployDate: TODAY
  secretKey: somethingNew

imagePullSecrets:
  - name: gitlab

ingress:
  enabled: true 
  hosts:
    - $$PROJECT_NAME$$-prod.my.hostname.com
  tls: 
    - hosts:
      - $$PROJECT_NAME$$-prod.my.hostname.com
      secretName: $$PROJECT_NAME$$-prod-tls
