
appImageTag: master

postgresql:
  image:
    pullPolicy: Always
  persistence:
    storageClass: nfs-client
  postgresqlPassword: SETAPASSWORD

nginx:
  image:
    pullPolicy: Always
  addLabels:
    deployDate: CISetDate

app:
  image:
    pullPolicy: Always
  addLabels:
    deployDate: CISetDate
  secretKey: SECRET_KEY

imagePullSecrets:
  - name: gitlab

ingress:
  enabled: true 
  hosts:
    - $$PROJECT_NAME$$-master.my.hostname.com
  tls: 
    - hosts:
      - $$PROJECT_NAME$$-master.my.hostname.com
      secretName: $$PROJECT_NAME$$-master-tls
