#!/bin/bash
docker pull mvantellingen/python-lint
docker-compose up -d db
docker-compose up -d redis
docker-compose run --no-deps $$PROJECT_NAME$$-app python manage.py makemigrations
echo "########### Django Test and Coverage"
docker-compose run --no-deps \
    -v "$PWD":/report \
    $$PROJECT_NAME$$-app \
    /bin/sh -c "coverage run --source='.' manage.py test && coverage report && coverage xml -o .coverage.xml && pycobertura show --format html --output /report/coverage.html .coverage.xml"
echo "########### Helm Lint"
helm lint charts/$$PROJECT_NAME$$/
echo "########### Python Lint (flake8)"
docker run --volume "$PWD":/code mvantellingen/python-lint flake8 app/
echo "########### Done"
