version: '3.7'

services:
  $$PROJECT_NAME$$-app:
    build: ./app
    command: gunicorn $$PROJECT_NAME$$.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    environment:
      - SECRET_KEY=$$SECRET_KEY$$
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - REDIS_CONNSTR=redis://redis:6379/1
    depends_on:
      - db
      - redis
  db:
    image: postgres:$$POSTGRES_VER$$-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
  redis:
    image: redis:$$REDIS_VER$$-alpine
  nginx:
    build: ./nginx
    environment:
      - APP_DNS_NAME=$$PROJECT_NAME$$-app
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8000:80
    depends_on:
      - $$PROJECT_NAME$$-app

volumes:
  db_data:
  static_volume:
  media_volume:
